### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by njgheorghita** [ethpm/ethpm.js#27] opened 2019-09-09 21:14 UTC
Can we get this released / available for install via npm? I've been building off a local copy for the remix plugin, but it would be nice to start building off the master version. Happy to help in any way possible - just let me know what steps I should take.

**Comment by gnidan** [comment] 2019-09-09 22:03
Yeah! There was something blocking this in ethpm-spec... in fact, I think this is a duplicate of #1 (or maybe just related)

I'll add this to my to-dos this week

**Closed** 2019-10-29 03:35 UTC
